### ISSUE TITLE
Repeating `font-family` calls

### ISSUE THREAD

**Issue by heyrygar** [filamentgroup/a-font-garde#4]
First of all, kudos on creating an accessible solution for icons. I work for a University that is of high priority for us. I have a couple questions:

I'm curious about the following code in the `markup.html` CSS: 

``` CSS
        /***************************
         * Fallback Bitmap
         ***************************/
        .icon-fallback-img .icon-hamburger {
                width: 1em;
                height: 1em;
                /* Note: BB5 doesn’t support background-images on pseudo-elements */
                background: url("fonts/png/hamburger.png") no-repeat;
        }
        /* A-Grade */
        .supports-fontface .icon-fallback-img .icon-hamburger:before {
                font-family: icomoon;
                content: "\e601";
        }
```

In particular, the `font-family` call—is it necessary to every icon on img fallback? Or, can we get away with just calling `font-family` once earlier in the code? For example:

``` CSS
.supports-fontface.supports-icomoon .icon { font-family: 'icomoon'; }
```

Would that cause any conflicts? I also noticed that for img fallback you only need `.supports-fontface` and not `.supports-icomoon` which is different from the default. Is that intentional? I apologize if my questions are elementary, I'm just trying to wrap my head around this as I write my customization and add multiple icons. Many thanks.
